name: XRechnung Validator
on:
  workflow_dispatch:
    inputs:
      file:
        default: './test/data/out/01.01a-INVOICE_uncefact.xml'
        description: 'XML file to validation'
        required: true
      validator_version:
        default: '1.5.0'
        description: 'KoSIT Validator version'
        options:
          - '1.5.0'
        required: true
        type: choice

jobs:
  validation_tool:
    env:
      INPUT_FILE: ${{ inputs.file }}
      VALIDATOR_VERSION: ${{ inputs.validator_version }}
      VALIDATOR_JAR_FILE: "validationtool-${{ inputs.validator_version }}-standalone.jar"
    name: Validation tool
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Check if the input file exists
        run: |
          if [[ -f "$INPUT_FILE" ]]; then
            echo "$INPUT_FILE exists."
          else
            echo "$INPUT_FILE does not exist."
            exit 1
          fi
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'
      - name: Download validator
        run: curl -L "https://github.com/itplr-kosit/validator/releases/download/v$VALIDATOR_VERSION/validator-$VALIDATOR_VERSION-distribution.zip" --output validator.zip
      - name: Download configuration
        run: curl -L "https://github.com/itplr-kosit/validator-configuration-xrechnung/releases/download/release-2023-11-15/validator-configuration-xrechnung_3.0.1_2023-11-15.zip" --output validator-configuration.zip
      - name: Unzip validator
        run: unzip -n validator.zip "$VALIDATOR_JAR_FILE"
      - name: Unzip configuration
        run: unzip -n validator-configuration.zip
      - name: Run Validator
        id: validator
        run: java -jar "$VALIDATOR_JAR_FILE" -s scenarios.xml -r "${PWD}" -h "$INPUT_FILE"
      - name: Upload report if failed
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: report
          path: "*-report*"
